<?php
namespace App\Services;
use App\Models\{Purchase,PurchaseItem,PurchaseReturn,Product,StockMovement,Supplier,Warehouse,WarehouseStock};
use Illuminate\Database\DatabaseManager;
use Illuminate\Validation\ValidationException;
class PurchasingService {
 public function __construct(private DatabaseManager $db, private AuditLogger $audit) {}
 public function createPurchase(Supplier $supplier, Warehouse $warehouse, array $items, float $discount, float $tax, ?string $expectedAt, ?string $note, $request): Purchase {
  return $this->db->transaction(function() use($supplier,$warehouse,$items,$discount,$tax,$expectedAt,$note,$request){
   $subtotal=0;$clean=[];
   foreach($items as $row){$product=Product::whereKey((int)$row['product_id'])->where('is_active',true)->first();if(!$product)throw ValidationException::withMessages(['items'=>'One or more products are unavailable.']);$qty=(float)$row['quantity'];$cost=(float)$row['unit_cost'];if($qty<=0||$cost<0)throw ValidationException::withMessages(['items'=>'Purchase quantities must be positive and unit costs cannot be negative.']);$line=round($qty*$cost,2);$subtotal+=$line;$clean[]=['product'=>$product,'quantity'=>$qty,'unit_cost'=>$cost,'line_total'=>$line];}
   $discount=max(0,$discount);$tax=max(0,$tax);$total=round($subtotal-$discount+$tax,2);if($total<0)throw ValidationException::withMessages(['discount'=>'Discount cannot exceed the subtotal.']);
   $no='PO-'.now()->format('YmdHis').'-'.random_int(1000,9999);$purchase=Purchase::create(['purchase_no'=>$no,'supplier_id'=>$supplier->id,'warehouse_id'=>$warehouse->id,'user_id'=>$request->user()?->id,'status'=>'draft','subtotal'=>$subtotal,'discount'=>$discount,'tax'=>$tax,'total'=>$total,'expected_at'=>$expectedAt,'note'=>$note]);
   foreach($clean as $row)$purchase->items()->create(['product_id'=>$row['product']->id,'quantity'=>$row['quantity'],'unit_cost'=>$row['unit_cost'],'line_total'=>$row['line_total']]);
   $this->audit->record($request,'purchasing.purchase_created','success',['purchase_id'=>$purchase->id,'purchase_no'=>$no,'total'=>$total]);return $purchase->load(['supplier','warehouse','items.product']);
  });
 }
 public function markOrdered(Purchase $purchase,$request): Purchase { if($purchase->status!=='draft')throw ValidationException::withMessages(['status'=>'Only draft purchases can be ordered.']);$purchase->update(['status'=>'ordered','ordered_at'=>now()]);$this->audit->record($request,'purchasing.purchase_ordered','success',['purchase_id'=>$purchase->id,'purchase_no'=>$purchase->purchase_no]);return $purchase->fresh(); }
 public function receive(Purchase $purchase,array $received,$request): Purchase {
  return $this->db->transaction(function() use($purchase,$received,$request){
   $purchase=Purchase::whereKey($purchase->id)->lockForUpdate()->firstOrFail();if(in_array($purchase->status,['cancelled','received'],true))throw ValidationException::withMessages(['status'=>'This purchase cannot receive additional stock.']);$warehouse=Warehouse::findOrFail($purchase->warehouse_id);$receivedAny=false;
   foreach($received as $row){$qty=(float)$row['quantity'];if($qty<=0)continue;$item=PurchaseItem::whereKey((int)$row['purchase_item_id'])->where('purchase_id',$purchase->id)->lockForUpdate()->first();if(!$item)throw ValidationException::withMessages(['items'=>'Invalid purchase item.']);$remaining=(float)$item->quantity-(float)$item->received_quantity;if($qty>$remaining+0.0001)throw ValidationException::withMessages(['items'=>"Receiving quantity exceeds the remaining quantity for {$item->product->name}."]);$stock=WarehouseStock::where('product_id',$item->product_id)->where('warehouse_id',$warehouse->id)->lockForUpdate()->first();if(!$stock)$stock=WarehouseStock::create(['product_id'=>$item->product_id,'warehouse_id'=>$warehouse->id,'quantity'=>0]);$new=(float)$stock->quantity+$qty;$stock->update(['quantity'=>$new]);$item->update(['received_quantity'=>(float)$item->received_quantity+$qty]);StockMovement::create(['product_id'=>$item->product_id,'warehouse_id'=>$warehouse->id,'user_id'=>$request->user()?->id,'type'=>'purchase_receive','quantity'=>$qty,'balance_after'=>$new,'reference'=>$purchase->purchase_no,'note'=>'Purchase receiving']);$receivedAny=true; }
   if(!$receivedAny)throw ValidationException::withMessages(['items'=>'Enter at least one receiving quantity.']);$purchase->load('items');$complete=$purchase->items->every(fn($i)=>(float)$i->received_quantity >= (float)$i->quantity);$hasReceived=$purchase->items->contains(fn($i)=>(float)$i->received_quantity>0);$purchase->update(['status'=>$complete?'received':'partial','received_at'=>$complete?now():$purchase->received_at]);$this->audit->record($request,'purchasing.stock_received','success',['purchase_id'=>$purchase->id,'purchase_no'=>$purchase->purchase_no,'status'=>$purchase->status]);return $purchase->fresh(['supplier','warehouse','items.product']);
  });
 }
 public function returnStock(Purchase $purchase,array $returns,?string $reason,$request): PurchaseReturn {
  return $this->db->transaction(function() use($purchase,$returns,$reason,$request){
   $purchase=Purchase::whereKey($purchase->id)->lockForUpdate()->firstOrFail();if($purchase->status==='cancelled')throw ValidationException::withMessages(['status'=>'Cancelled purchases cannot have stock returned.']);$total=0;$clean=[];$warehouse=Warehouse::findOrFail($purchase->warehouse_id);
   foreach($returns as $row){$qty=(float)$row['quantity'];if($qty<=0)continue;$item=PurchaseItem::whereKey((int)$row['purchase_item_id'])->where('purchase_id',$purchase->id)->lockForUpdate()->first();if(!$item)throw ValidationException::withMessages(['items'=>'Invalid purchase item.']);$available=(float)$item->received_quantity-(float)$item->returned_quantity;if($qty>$available+0.0001)throw ValidationException::withMessages(['items'=>"Return quantity exceeds received quantity for {$item->product->name}."]);$stock=WarehouseStock::where('product_id',$item->product_id)->where('warehouse_id',$warehouse->id)->lockForUpdate()->first();if(!$stock||(float)$stock->quantity<$qty)throw ValidationException::withMessages(['items'=>"Insufficient current stock to return {$item->product->name}."]);$line=round($qty*(float)$item->unit_cost,2);$total+=$line;$clean[]=['item'=>$item,'quantity'=>$qty,'unit_cost'=>(float)$item->unit_cost,'line_total'=>$line,'stock'=>$stock];}
   if(!$clean)throw ValidationException::withMessages(['items'=>'Enter at least one return quantity.']);$no='PR-'.now()->format('YmdHis').'-'.random_int(1000,9999);$ret=PurchaseReturn::create(['return_no'=>$no,'purchase_id'=>$purchase->id,'supplier_id'=>$purchase->supplier_id,'warehouse_id'=>$warehouse->id,'user_id'=>$request->user()?->id,'total'=>$total,'reason'=>$reason]);foreach($clean as $row){$ret->items()->create(['purchase_item_id'=>$row['item']->id,'quantity'=>$row['quantity'],'unit_cost'=>$row['unit_cost'],'line_total'=>$row['line_total']]);$new=(float)$row['stock']->quantity-$row['quantity'];$row['stock']->update(['quantity'=>$new]);$row['item']->update(['returned_quantity'=>(float)$row['item']->returned_quantity+$row['quantity']]);StockMovement::create(['product_id'=>$row['item']->product_id,'warehouse_id'=>$warehouse->id,'user_id'=>$request->user()?->id,'type'=>'purchase_return','quantity'=>-$row['quantity'],'balance_after'=>$new,'reference'=>$no,'note'=>$reason]);}$this->audit->record($request,'purchasing.purchase_returned','success',['purchase_id'=>$purchase->id,'return_no'=>$no,'total'=>$total]);return $ret->load(['purchase','items.purchaseItem.product']);
  });
 }
}
