@extends('layouts.app')
@section('content')
<div class="page-head"><div><div class="eyebrow">Purchasing</div><h1>New purchase order</h1><p>Create a supplier order. Stock changes only when receiving is completed.</p></div><a class="btn" href="{{ route('purchases.index') }}">Back</a></div>
<form method="POST" action="{{ route('purchases.store') }}" id="purchase-form">@csrf
<div class="grid-2"><div class="panel"><div class="panel-head"><h2>Order details</h2></div><div class="form-grid"><label>Supplier<select name="supplier_id" required><option value="">Select supplier</option>@foreach($suppliers as $s)<option value="{{ $s->id }}">{{ $s->name }} ({{ $s->code }})</option>@endforeach</select></label><label>Receiving warehouse<select name="warehouse_id" required><option value="">Select warehouse</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></label><label>Expected date<input type="date" name="expected_at"></label><label>Note<input name="note" maxlength="1000"></label></div></div>
<div class="panel"><div class="panel-head"><h2>Totals</h2></div><div class="summary"><div><span>Subtotal</span><strong id="subtotal">₱0.00</strong></div><label>Discount <input type="number" step="0.01" min="0" name="discount" id="discount" value="0"></label><label>Tax <input type="number" step="0.01" min="0" name="tax" id="tax" value="0"></label><div class="grand"><span>Total</span><strong id="grand">₱0.00</strong></div></div></div></div>
<div class="panel"><div class="panel-head"><h2>Items</h2><button type="button" class="btn small" onclick="addRow()">+ Add item</button></div><div class="table-wrap"><table id="items"><thead><tr><th>Product</th><th>Quantity</th><th>Unit cost</th><th>Line total</th><th></th></tr></thead><tbody></tbody></table></div><div class="form-actions"><button class="btn primary">Create purchase order</button></div></div>
</form>
<script>
const products=@json($products);let idx=0;
function addRow(){const i=idx++;const opts=products.map(p=>`<option value="${p.id}" data-cost="${p.cost_price}">${p.name} (${p.sku})</option>`).join('');document.querySelector('#items tbody').insertAdjacentHTML('beforeend',`<tr><td><select name="items[${i}][product_id]" onchange="syncCost(this)" required><option value="">Select product</option>${opts}</select></td><td><input class="line-qty" type="number" step="0.001" min="0.001" name="items[${i}][quantity]" value="1" oninput="calc()" required></td><td><input class="line-cost" type="number" step="0.01" min="0" name="items[${i}][unit_cost]" value="0" oninput="calc()" required></td><td class="line-total">₱0.00</td><td><button type="button" class="btn small danger-btn" onclick="this.closest('tr').remove();calc()">Remove</button></td></tr>`);}
function syncCost(s){const o=s.options[s.selectedIndex];s.closest('tr').querySelector('.line-cost').value=o?.dataset.cost||0;calc();}
function calc(){let sub=0;document.querySelectorAll('#items tbody tr').forEach(r=>{const q=parseFloat(r.querySelector('.line-qty').value)||0,c=parseFloat(r.querySelector('.line-cost').value)||0,l=q*c;sub+=l;r.querySelector('.line-total').textContent='₱'+l.toFixed(2)});const d=parseFloat(document.querySelector('#discount').value)||0,t=parseFloat(document.querySelector('#tax').value)||0;document.querySelector('#subtotal').textContent='₱'+sub.toFixed(2);document.querySelector('#grand').textContent='₱'+Math.max(0,sub-d+t).toFixed(2)}
document.querySelector('#discount').addEventListener('input',calc);document.querySelector('#tax').addEventListener('input',calc);addRow();
</script>
@endsection
