@extends('layouts.app')
@section('content')
<div class="page-head"><div><div class="eyebrow">Purchase order</div><h1>{{ $purchase->purchase_no }}</h1><p>{{ $purchase->supplier->name }} · {{ $purchase->warehouse->name }}</p></div><a class="btn" href="{{ route('purchases.index') }}">All purchases</a></div>
@if(session('success'))<div class="notice success">{{ session('success') }}</div>@endif
<div class="metrics"><article><span>Status</span><strong>{{ ucfirst($purchase->status) }}</strong><small>{{ $purchase->expected_at?->format('M d, Y') ?: 'No expected date' }}</small></article><article><span>Subtotal</span><strong>₱{{ number_format($purchase->subtotal,2) }}</strong><small>{{ $purchase->items->count() }} line(s)</small></article><article><span>Received</span><strong>{{ number_format($purchase->items->sum('received_quantity'),3) }}</strong><small>units received</small></article><article><span>Returns</span><strong>{{ $purchase->returns->count() }}</strong><small>return document(s)</small></article></div>
@if($purchase->status==='draft')<div class="notice warning">This order is still a draft. Mark it as ordered before receiving stock.<form method="POST" action="{{ route('purchases.order',$purchase) }}" style="display:inline;margin-left:10px">@csrf<button class="btn primary small">Mark ordered</button></form></div>@endif
<div class="panel"><div class="panel-head"><h2>Items</h2><span>Total ₱{{ number_format($purchase->total,2) }}</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Ordered</th><th>Received</th><th>Returned</th><th>Unit cost</th><th>Line</th></tr></thead><tbody>@foreach($purchase->items as $item)<tr><td><strong>{{ $item->product->name }}</strong><small>{{ $item->product->sku }}</small></td><td>{{ number_format($item->quantity,3) }}</td><td>{{ number_format($item->received_quantity,3) }}</td><td>{{ number_format($item->returned_quantity,3) }}</td><td>₱{{ number_format($item->unit_cost,2) }}</td><td>₱{{ number_format($item->line_total,2) }}</td></tr>@endforeach</tbody></table></div></div>
@if(in_array($purchase->status,['ordered','partial']))<div class="panel"><div class="panel-head"><h2>Receive stock</h2><span>Only remaining quantities can be received.</span></div><form method="POST" action="{{ route('purchases.receive',$purchase) }}">@csrf<div class="table-wrap"><table><thead><tr><th>Product</th><th>Remaining</th><th>Receive now</th></tr></thead><tbody>@foreach($purchase->items as $item)@php($remaining=(float)$item->quantity-(float)$item->received_quantity)<tr><td>{{ $item->product->name }}</td><td>{{ number_format(max(0,$remaining),3) }}</td><td><input type="hidden" name="items[{{ $item->id }}][purchase_item_id]" value="{{ $item->id }}"><input type="number" class="form-grid-input" step="0.001" min="0" max="{{ max(0,$remaining) }}" name="items[{{ $item->id }}][quantity]" value="0"></td></tr>@endforeach</tbody></table></div><div class="form-actions"><button class="btn primary">Receive stock</button></div></form></div>@endif
@if($purchase->items->sum('received_quantity')>0 && $purchase->status!=='cancelled')<div class="panel"><div class="panel-head"><h2>Return received stock</h2><span>Cannot exceed received minus already returned.</span></div><form method="POST" action="{{ route('purchases.return',$purchase) }}">@csrf<div class="form-grid"><label>Reason<input name="reason" maxlength="1000" placeholder="Damaged, incorrect item, etc."></label></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Available to return</th><th>Return now</th></tr></thead><tbody>@foreach($purchase->items as $item)@php($available=(float)$item->received_quantity-(float)$item->returned_quantity)<tr><td>{{ $item->product->name }}</td><td>{{ number_format(max(0,$available),3) }}</td><td><input type="hidden" name="items[{{ $item->id }}][purchase_item_id]" value="{{ $item->id }}"><input type="number" class="form-grid-input" step="0.001" min="0" max="{{ max(0,$available) }}" name="items[{{ $item->id }}][quantity]" value="0"></td></tr>@endforeach</tbody></table></div><div class="form-actions"><button class="btn danger-btn">Process return</button></div></form></div>@endif
@endsection
