<?php namespace App\Http\Controllers\Inventory;
use App\Http\Controllers\Controller; use App\Models\{Product,Category,Brand,Unit}; use App\Services\AuditLogger; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class ProductController extends Controller {
 public function index(Request $r){$q=Product::with(['category','brand','unit','stocks']); if($r->filled('search')){$s=$r->string('search');$q->where(fn($x)=>$x->where('name','like',"%$s%")->orWhere('sku','like',"%$s%"));} if($r->filled('category_id'))$q->where('category_id',$r->integer('category_id')); $products=$q->latest()->paginate(12)->withQueryString(); return view('inventory.products.index',compact('products'));}
 public function create(){return view('inventory.products.create',['categories'=>Category::where('is_active',true)->orderBy('name')->get(),'brands'=>Brand::where('is_active',true)->orderBy('name')->get(),'units'=>Unit::orderBy('name')->get()]);}
 public function store(Request $r, AuditLogger $audit){$data=$r->validate(['name'=>['required','string','max:150'],'sku'=>['required','string','max:80','alpha_dash','unique:products,sku'],'category_id'=>['nullable','integer','exists:categories,id'],'brand_id'=>['nullable','integer','exists:brands,id'],'unit_id'=>['nullable','integer','exists:units,id'],'cost_price'=>['required','numeric','min:0','max:999999999'],'selling_price'=>['required','numeric','min:0','max:999999999'],'reorder_level'=>['required','numeric','min:0','max:999999999'],'description'=>['nullable','string','max:5000']]); $p=Product::create($data); $audit->record($r,'inventory.product_created','success',['product_id'=>$p->id,'sku'=>$p->sku]); return redirect()->route('inventory.products.index')->with('success','Product created successfully.');}
 public function edit(Product $product){return view('inventory.products.edit',['product'=>$product,'categories'=>Category::where('is_active',true)->orderBy('name')->get(),'brands'=>Brand::where('is_active',true)->orderBy('name')->get(),'units'=>Unit::orderBy('name')->get()]);}
 public function update(Request $r, Product $product, AuditLogger $audit){$data=$r->validate(['name'=>['required','string','max:150'],'sku'=>['required','string','max:80','alpha_dash',Rule::unique('products','sku')->ignore($product->id)],'category_id'=>['nullable','integer','exists:categories,id'],'brand_id'=>['nullable','integer','exists:brands,id'],'unit_id'=>['nullable','integer','exists:units,id'],'cost_price'=>['required','numeric','min:0'],'selling_price'=>['required','numeric','min:0'],'reorder_level'=>['required','numeric','min:0'],'description'=>['nullable','string','max:5000'],'is_active'=>['nullable','boolean']]); $product->update($data); $audit->record($r,'inventory.product_updated','success',['product_id'=>$product->id]); return back()->with('success','Product updated.');}
 public function destroy(Product $product, AuditLogger $audit, Request $r){$id=$product->id;$product->delete();$audit->record($r,'inventory.product_deleted','success',['product_id'=>$id]);return back()->with('success','Product deleted.');}
}
