@extends('layouts.app')
@section('content')
<div class="page-head"><div><span class="eyebrow">Point of sale</span><h1>New sale</h1><p>Fast checkout with server-side stock validation.</p></div><a class="btn" href="{{ route('sales.index') }}">Transactions</a></div>
<form method="POST" action="{{ route('sales.store') }}" id="pos-form" class="pos-layout">@csrf
<section class="panel product-picker"><div class="panel-head"><div><h2>Products</h2><small>Select an item to add it to the cart.</small></div><input class="search" id="product-search" placeholder="Search name or SKU" autocomplete="off"></div><div class="product-grid" id="product-grid">@foreach($products as $product)<button type="button" class="product-card" data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-sku="{{ $product->sku }}" data-price="{{ $product->selling_price }}"><strong>{{ $product->name }}</strong><small>{{ $product->sku }}</small><span>₱{{ number_format($product->selling_price,2) }}</span></button>@endforeach</div></section>
<aside class="panel cart"><div class="panel-head"><div><h2>Cart</h2><span id="cart-count">0 items</span></div></div><div id="cart-lines" class="cart-lines"><div class="empty">Add products to begin.</div></div><div class="checkout"><label>Customer<select name="customer_id"><option value="">Walk-in customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} · {{ $customer->code }}</option>@endforeach</select></label><label>Warehouse<select name="warehouse_id" required>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></label><label>Customer<input name="customer_name" maxlength="150" placeholder="Walk-in customer"></label><div class="summary"><div><span>Subtotal</span><strong id="subtotal">₱0.00</strong></div><label>Discount<input type="number" name="discount" id="discount" min="0" step="0.01" value="0"></label><label>Tax<input type="number" name="tax" id="tax" min="0" step="0.01" value="0"></label><div class="grand"><span>Total</span><strong id="total">₱0.00</strong></div></div><label>Payment method<select name="payment_method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank">Bank</option><option value="gcash">GCash</option></select></label><label>Amount paid<input type="number" name="paid" id="paid" min="0" step="0.01" required value="0"></label><div class="change">Change <strong id="change">₱0.00</strong></div><button class="btn primary wide" type="submit">Complete sale</button></div></aside>
</form>
<script>
const cart=new Map(), grid=document.getElementById('product-grid'), lines=document.getElementById('cart-lines');
function money(n){return '₱'+Number(n).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}
function render(){let subtotal=0;lines.innerHTML='';if(!cart.size) lines.innerHTML='<div class="empty">Add products to begin.</div>';let i=0;for(const [id,p] of cart){const line=p.price*p.qty;subtotal+=line;lines.insertAdjacentHTML('beforeend',`<div class="cart-line"><div><strong>${p.name}</strong><small>${p.sku} · ${money(p.price)}</small></div><div class="qty"><button type="button" data-act="minus" data-id="${id}">−</button><input data-act="qty" data-id="${id}" type="number" min="0.001" step="0.001" value="${p.qty}"><button type="button" data-act="plus" data-id="${id}">+</button></div><strong>${money(line)}</strong><input type="hidden" name="items[${i}][product_id]" value="${id}"><input type="hidden" name="items[${i}][quantity]" value="${p.qty}"></div>`);i++}document.getElementById('cart-count').textContent=cart.size+' item'+(cart.size===1?'':'s');document.getElementById('subtotal').textContent=money(subtotal);const total=Math.max(0,subtotal-Number(document.getElementById('discount').value||0)+Number(document.getElementById('tax').value||0));document.getElementById('total').textContent=money(total);document.getElementById('change').textContent=money(Math.max(0,Number(document.getElementById('paid').value||0)-total));}
grid.addEventListener('click',e=>{const b=e.target.closest('.product-card');if(!b)return;const id=b.dataset.id,p=cart.get(id)||{name:b.dataset.name,sku:b.dataset.sku,price:Number(b.dataset.price),qty:0};p.qty+=1;cart.set(id,p);render();});lines.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const p=cart.get(b.dataset.id);if(!p)return;p.qty+=b.dataset.act==='plus'?1:-1;if(p.qty<=0)cart.delete(b.dataset.id);render();});lines.addEventListener('input',e=>{if(e.target.dataset.act!=='qty')return;const p=cart.get(e.target.dataset.id);if(!p)return;p.qty=Number(e.target.value);if(p.qty<=0)cart.delete(e.target.dataset.id);render();});document.getElementById('product-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();grid.querySelectorAll('.product-card').forEach(b=>b.hidden=!(b.dataset.name.toLowerCase().includes(q)||b.dataset.sku.toLowerCase().includes(q)));});['discount','tax','paid'].forEach(id=>document.getElementById(id).addEventListener('input',render));document.getElementById('pos-form').addEventListener('submit',e=>{if(!cart.size){e.preventDefault();alert('Add at least one product.');}});render();
</script>
@endsection
